import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "iphone-15-pro-256",
    title: "Apple iPhone 15 Pro 256 GB",
    category: "Смартфони",
    subtitle: "6.1\" OLED · 256 GB · 5G",
    rating: 4.8,
    reviewCount: 1240,
    image: "📱",
    bestPrice: 29900,
    oldPrice: 44999,
    score: 94,
    highlights: ["256 GB", "ProMotion 120 Гц", "титановий корпус"],
    caution: "Для б/в перевіряй стан батареї, Face ID та IMEI перед оплатою.",
    aiSummary: "SmartBuy окремо показує магазинні та приватні пропозиції, щоб дешевий б/в варіант не виглядав як новий товар із магазину.",
    offers: [
      { id: "ip15p-prom", store: "Prom.ua", marketplace: "Prom.ua", sellerType: "store", condition: "new", price: 38999, delivery: "доставка по Україні", warranty: "12 міс.", trusted: true, sellerName: "магазин на Prom", url: "https://prom.ua/ua/search?search_term=iPhone%2015%20Pro%20256" },
      { id: "ip15p-rozetka", store: "Rozetka", marketplace: "Rozetka", sellerType: "store", condition: "new", price: 41999, delivery: "доставка / самовивіз", warranty: "12 міс.", trusted: true, sellerName: "Rozetka", url: "https://rozetka.com.ua/ua/search/?text=iPhone%2015%20Pro%20256" },
      { id: "ip15p-olx1", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 31500, delivery: "OLX Доставка / зустріч", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Київ", postedAt: "сьогодні", negotiable: true, url: "https://www.olx.ua/uk/list/q-iphone-15-pro-256/" },
      { id: "ip15p-olx2", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 29900, delivery: "OLX Доставка / зустріч", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Рівненська область", postedAt: "вчора", negotiable: true, url: "https://www.olx.ua/uk/list/q-iphone-15-pro-256/" },
    ]
  },
  {
    id: "lenovo-loq-15",
    title: "Lenovo LOQ 15 Gaming",
    category: "Ноутбуки",
    subtitle: "15.6\" · Ryzen 7 · RTX 4060/5060 · 16 GB",
    rating: 4.6,
    reviewCount: 418,
    image: "💻",
    bestPrice: 33500,
    oldPrice: 44999,
    score: 91,
    highlights: ["ігрова RTX", "16 GB RAM", "хороше охолодження"],
    caution: "У приватних оголошеннях уточнюй точну відеокарту та стан батареї.",
    aiSummary: "Для ігрового ноутбука різниця між новим і б/в може бути значною, але конфігурацію треба звіряти дуже уважно.",
    offers: [
      { id: "loq-telemart", store: "TELEMART", marketplace: "TELEMART", sellerType: "store", condition: "new", price: 41999, delivery: "1–3 дні", warranty: "24 міс.", trusted: true, sellerName: "TELEMART", url: "https://telemart.ua/ua/search/?search=Lenovo%20LOQ%2015" },
      { id: "loq-hotline", store: "Hotline", marketplace: "Hotline", sellerType: "store", condition: "new", price: 40490, delivery: "залежить від магазину", warranty: "залежить від магазину", trusted: true, sellerName: "магазини Hotline", url: "https://hotline.ua/ua/sr/?q=Lenovo%20LOQ%2015" },
      { id: "loq-olx", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 33500, delivery: "OLX Доставка / зустріч", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Львів", postedAt: "2 дні тому", negotiable: true, url: "https://www.olx.ua/uk/list/q-lenovo-loq-15/" },
    ]
  },
  {
    id: "makita-dhp486",
    title: "Makita DHP486",
    category: "Інструменти",
    subtitle: "18 V · ударний дриль-шуруповерт",
    rating: 4.9,
    reviewCount: 682,
    image: "🛠️",
    bestPrice: 5400,
    oldPrice: 8999,
    score: 96,
    highlights: ["18 V", "безщітковий двигун", "професійна серія"],
    caution: "На OLX звертай увагу, чи це оригінал, чи копія, і чи входять акумулятори.",
    aiSummary: "Для інструментів особливо важливо порівнювати не тільки ціну, а й комплект: body-only та комплект з АКБ можуть відрізнятися на кілька тисяч гривень.",
    offers: [
      { id: "makita-epic", store: "Епіцентр", marketplace: "Епіцентр", sellerType: "store", condition: "new", price: 8799, delivery: "доставка / самовивіз", warranty: "36 міс.", trusted: true, sellerName: "Епіцентр", url: "https://epicentrk.ua/ua/search/?q=Makita%20DHP486" },
      { id: "makita-prom", store: "Prom.ua", marketplace: "Prom.ua", sellerType: "store", condition: "new", price: 7490, delivery: "доставка по Україні", warranty: "залежить від продавця", trusted: true, sellerName: "продавці Prom", url: "https://prom.ua/ua/search?search_term=Makita%20DHP486" },
      { id: "makita-olx", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 5400, delivery: "OLX Доставка / зустріч", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Луцьк", postedAt: "сьогодні", negotiable: true, url: "https://www.olx.ua/uk/list/q-makita-dhp486/" },
    ]
  },
  {
    id: "roborock-q8-max",
    title: "Roborock Q8 Max+",
    category: "Для дому",
    subtitle: "робот-пилосос · станція самоочищення",
    rating: 4.8,
    reviewCount: 932,
    image: "🤖",
    bestPrice: 11800,
    oldPrice: 16999,
    score: 95,
    highlights: ["самоочищення", "LiDAR", "добре збирає шерсть"],
    caution: "Для б/в перевіряй ресурс батареї та стан щіток/станції.",
    aiSummary: "Новий варіант безпечніший через гарантію, але на приватному ринку іноді є майже нові комплекти дешевше.",
    offers: [
      { id: "q8-allo", store: "ALLO", marketplace: "ALLO", sellerType: "store", condition: "new", price: 15999, delivery: "доставка / самовивіз", warranty: "12 міс.", trusted: true, sellerName: "ALLO", url: "https://allo.ua/ua/catalogsearch/result/?q=Roborock%20Q8%20Max%2B" },
      { id: "q8-comfy", store: "COMFY", marketplace: "COMFY", sellerType: "store", condition: "new", price: 16499, delivery: "доставка / самовивіз", warranty: "12 міс.", trusted: true, sellerName: "COMFY", url: "https://comfy.ua/ua/search/?q=Roborock%20Q8%20Max%2B" },
      { id: "q8-olx", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 11800, delivery: "OLX Доставка / зустріч", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Одеса", postedAt: "3 дні тому", negotiable: true, url: "https://www.olx.ua/uk/list/q-roborock-q8-max/" },
    ]
  },
  {
    id: "samsung-s24-ultra-256",
    title: "Samsung Galaxy S24 Ultra 256 GB",
    category: "Смартфони",
    subtitle: "6.8\" AMOLED · 256 GB · S Pen",
    rating: 4.8,
    reviewCount: 1580,
    image: "📱",
    bestPrice: 27500,
    oldPrice: 45999,
    score: 93,
    highlights: ["S Pen", "120 Гц", "сильний зум"],
    caution: "У приватних оголошеннях перевіряй дисплей на вигорання і наявність гарантійних документів.",
    aiSummary: "Модель уже добре представлена і в магазинах, і на вторинному ринку, тому тут особливо корисно бачити обидва сегменти поруч.",
    offers: [
      { id: "s24-rozetka", store: "Rozetka", marketplace: "Rozetka", sellerType: "store", condition: "new", price: 38999, delivery: "доставка / самовивіз", warranty: "12 міс.", trusted: true, sellerName: "Rozetka", url: "https://rozetka.com.ua/ua/search/?text=Samsung%20S24%20Ultra%20256" },
      { id: "s24-allo", store: "ALLO", marketplace: "ALLO", sellerType: "store", condition: "new", price: 39999, delivery: "доставка / самовивіз", warranty: "12 міс.", trusted: true, sellerName: "ALLO", url: "https://allo.ua/ua/catalogsearch/result/?q=Samsung%20S24%20Ultra%20256" },
      { id: "s24-olx", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 27500, delivery: "OLX Доставка / зустріч", warranty: "можлива залишкова", trusted: false, sellerName: "приватний продавець", city: "Дніпро", postedAt: "сьогодні", negotiable: true, url: "https://www.olx.ua/uk/list/q-samsung-s24-ultra-256/" },
    ]
  },
  {
    id: "sony-55-120",
    title: "Sony BRAVIA 55\" 4K 120 Hz",
    category: "Телевізори",
    subtitle: "55\" · 4K · 120 Гц · HDMI 2.1",
    rating: 4.7,
    reviewCount: 443,
    image: "📺",
    bestPrice: 18900,
    oldPrice: 26999,
    score: 92,
    highlights: ["120 Гц", "HDMI 2.1", "підходить для PS5"],
    caution: "Б/в телевізор краще оглядати особисто: матриця, засвітки, биті пікселі.",
    aiSummary: "Для великої техніки приватна пропозиція може бути вигідною, але доставка та перевірка стану важливіші за різницю в ціні.",
    offers: [
      { id: "sony-foxtrot", store: "Foxtrot", marketplace: "Foxtrot", sellerType: "store", condition: "new", price: 24799, delivery: "доставка / самовивіз", warranty: "24 міс.", trusted: true, sellerName: "Foxtrot", url: "https://www.foxtrot.com.ua/uk/search?query=Sony%20BRAVIA%2055%20120Hz" },
      { id: "sony-hotline", store: "Hotline", marketplace: "Hotline", sellerType: "store", condition: "new", price: 23200, delivery: "залежить від магазину", warranty: "залежить від магазину", trusted: true, sellerName: "магазини Hotline", url: "https://hotline.ua/ua/sr/?q=Sony%20BRAVIA%2055%20120Hz" },
      { id: "sony-olx", store: "OLX", marketplace: "OLX", sellerType: "private", condition: "used", price: 18900, delivery: "самовивіз бажано", warranty: "без гарантії", trusted: false, sellerName: "приватний продавець", city: "Київ", postedAt: "5 днів тому", negotiable: true, url: "https://www.olx.ua/uk/list/q-sony-bravia-55/" },
    ]
  }
];
